version: '3'

services:
    db:
        image: postgres:12-alpine
        environment:
            POSTGRES_USER: posthog
            POSTGRES_DB: posthog
            POSTGRES_PASSWORD: posthog
        volumes:
            - ./docker/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
        ports:
            - '5432:5432'
    redis:
        image: 'redis:alpine'
        ports:
            - '6379:6379'
    clickhouse:
        # KEEP CLICKHOUSE-SERVER VERSION IN SYNC WITH
        # https://github.com/PostHog/charts-clickhouse/blob/main/charts/posthog/templates/clickhouse_instance.yaml#L88
        image: posthog/clickhouse:v21.9.2.17-stable
        depends_on:
            - kafka
            - zookeeper
        ports:
            - '8123:8123'
            - '9000:9000'
            - '9440:9440'
            - '9009:9009'
        volumes:
            - ./docker/clickhouse/idl:/idl
            - ./docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - ./docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml
            - ./docker/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    zookeeper:
        image: wurstmeister/zookeeper
    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - '9092:9092'
        environment:
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
