name: CI

on:
    - pull_request

jobs:
    code-quality:
        name: Code quality
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v1

            - name: Set up Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install package.json dependencies with Yarn
              run: yarn

            - name: Check formatting with prettier
              run: yarn prettier:check

            - name: Lint with ESLint
              run: yarn lint

    tests-clickhouse:
        name: Tests – ClickHouse + Kafka
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    # Maps port 6379 on service container to the host
                    # Needed because `redis` host is not discoverable for some reason
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            clickhouse:
                image: yandex/clickhouse-server
                ports:
                    - '8123:8123'
                    - '9000:9000'
                    - '9440:9440'
                    - '9009:9009'
            zookeeper:
                image: wurstmeister/zookeeper
            kafka:
                image: wurstmeister/kafka
                ports:
                    - '9092:9092'
                env:
                    KAFKA_ADVERTISED_HOST_NAME: kafka
                    sKAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        steps:
            - name: Check out Django server for database setup
              uses: actions/checkout@v2
              with:
                  repository: 'PostHog/posthog'
                  ref: 'fix-ch-compose' # TODO: remove this line to use master
                  path: 'posthog/'

            - name: Check out plugin server
              uses: actions/checkout@v2
              with:
                  path: 'plugin-server'

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install requirements.txt dependencies with pip
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -r posthog/requirements.txt

            - name: Set up ClickHouse
              env:
                  SECRET_KEY: 'abcdef' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  PRIMARY_DB: 'clickhouse'
                  CLICKHOUSE_HOST: 'localhost'
                  CLICKHOUSE_DATABASE: 'posthog_test'
                  CLICKHOUSE_SECURE: 'false'
                  CLICKHOUSE_VERIFY: 'false'
                  TEST: 'true'
              run: |
                  python posthog/manage.py clickhouse_test_setup

            - name: Install package.json dependencies with Yarn
              run: cd plugin-server && yarn

            - name: Test with Jest
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  REDIS_URL: 'redis://localhost'
              run: cd plugin-server && yarn test

            - name: Tear down ClickHouse
              env:
                  SECRET_KEY: 'abcdef' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  PRIMARY_DB: 'clickhouse'
                  CLICKHOUSE_HOST: 'localhost'
                  CLICKHOUSE_DATABASE: 'posthog_test'
                  CLICKHOUSE_SECURE: 'false'
                  CLICKHOUSE_VERIFY: 'false'
                  TEST: 'true'
              run: |
                  python posthog/manage.py clickhouse_test_teardown

    tests:
        name: Tests
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    # Maps port 6379 on service container to the host
                    # Needed because `redis` host is not discoverable for some reason
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Install package.json dependencies with Yarn
              run: yarn

            - name: Initiate database
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  REDIS_URL: 'redis://localhost'
              run: yarn task:init-test-db

            - name: Test with Jest
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  REDIS_URL: 'redis://localhost'
              run: yarn test

    benchmarks:
        name: Benchmarks
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: postgres
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    # Maps port 6379 on service container to the host
                    # Needed because `redis` host is not discoverable for some reason
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v1

            - name: Set up Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install package.json dependencies with Yarn
              run: yarn

            - name: Initiate database
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  REDIS_URL: 'redis://localhost'
              run: yarn task:init-test-db

            - name: Run benchmarks
              env:
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
                  REDIS_URL: 'redis://localhost'
              run: yarn benchmark
