name: CI

on:
    - pull_request

jobs:
    code-quality:
        name: Code quality
        runs-on: ubuntu-20.04

        steps:
            - uses: actions/checkout@v1

            - name: Set up Node 14
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: Install package.json dependencies with Yarn
              run: yarn

            - name: Check formatting with prettier
              run: yarn prettier:check

            - name: Lint with ESLint
              run: yarn lint

    tests-postgres:
        name: Tests / Postgres + Redis
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_posthog
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    - '6379:6379'
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            REDIS_URL: 'redis://localhost'

        steps:
            - name: Check out Django server for database setup
              uses: actions/checkout@v2
              with:
                  repository: 'PostHog/posthog'
                  path: 'posthog/'

            - name: Check out plugin server
              uses: actions/checkout@v2
              with:
                  path: 'plugin-server'

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - uses: actions/cache@v2
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ env.pythonLocation }}-${{ hashFiles('posthog/requirements.txt') }}

            - name: Install requirements.txt dependencies with pip
              run: |
                  pip install --upgrade pip
                  pip install --upgrade --upgrade-strategy eager -r posthog/requirements.txt

            - name: Set up databases
              env:
                  SECRET_KEY: 'abcdef' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/posthog'
                  TEST: 'true'
              run: python posthog/manage.py setup_test_environment

            - name: Install package.json dependencies with Yarn
              run: cd plugin-server && yarn

            - name: Test with Jest
              env:
                  # Below DB name has `test_` prepended, as that's how Django (ran above) creates the test DB
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/test_posthog'
                  REDIS_URL: 'redis://localhost'
              run: cd plugin-server && yarn test:postgres

    tests-clickhouse:
        name: Tests / ClickHouse + Kafka
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_posthog
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    - '6379:6379'
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
            zookeeper:
                image: wurstmeister/zookeeper
                ports:
                    - '2181:2181'
            kafka:
                image: wurstmeister/kafka
                ports:
                    - '9092:9092'
                env:
                    KAFKA_ADVERTISED_HOST_NAME: kafka
                    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

        env:
            REDIS_URL: 'redis://localhost'
            CLICKHOUSE_HOST: 'localhost'
            CLICKHOUSE_DATABASE: 'posthog_test'
            KAFKA_ENABLED: 'true'
            KAFKA_HOSTS: 'kafka:9092'

        steps:
            - name: Check out Django server for database setup
              uses: actions/checkout@v2
              with:
                  repository: 'PostHog/posthog'
                  path: 'posthog/'

            - name: Check out plugin server
              uses: actions/checkout@v2
              with:
                  path: 'plugin-server'

            - name: Install clickhouse db with .proto files
              run: |
                  docker run \
                    --detach \
                    --name clickhouse \
                    -p 8123:8123 \
                    -p 9000:9000 \
                    -p 9440:9440 \
                    -p 9009:9009 \
                    -v ${{ github.workspace }}/posthog/ee/idl:/idl \
                    -v ${{ github.workspace }}/posthog/docker/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d \
                    -v ${{ github.workspace }}/posthog/docker/clickhouse/config.xml:/etc/clickhouse-server/config.xml \
                    yandex/clickhouse-server

            - name: Fix Kafka Hostname
              run: |
                  sudo bash -c 'echo "127.0.0.1 kafka zookeeper redis" >> /etc/hosts'
                  ping -c 1 kafka
                  ping -c 1 zookeeper

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - uses: actions/cache@v2
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ env.pythonLocation }}-${{ hashFiles('posthog/requirements.txt') }}

            - name: Install requirements.txt dependencies with pip
              run: |
                  pip install --upgrade pip
                  pip install --upgrade --upgrade-strategy eager -r posthog/requirements.txt

            - name: Set up databases
              env:
                  SECRET_KEY: 'abcdef' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/posthog'
                  CLICKHOUSE_DATABASE: 'posthog_test'
                  PRIMARY_DB: 'clickhouse'
                  TEST: 'true'
              run: python posthog/manage.py setup_test_environment

            - name: Install package.json dependencies with Yarn
              run: cd plugin-server && yarn

            - name: Test with Jest
              env:
                  # Below DB name has `test_` prepended, as that's how Django (ran above) creates the test DB
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/test_posthog'
                  CLICKHOUSE_DATABASE: 'posthog_test'
                  REDIS_URL: 'redis://localhost'
              run: cd plugin-server && yarn test:clickhouse

    benchmarks-postgres:
        name: Benchmarks / Postgres + Redis
        runs-on: ubuntu-20.04

        services:
            postgres:
                image: postgres:12
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_posthog
                ports: ['5432:5432']
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis
                ports:
                    - '6379:6379'
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        env:
            REDIS_URL: 'redis://localhost'

        steps:
            - name: Check out Django server for database setup
              uses: actions/checkout@v2
              with:
                  repository: 'PostHog/posthog'
                  path: 'posthog/'

            - name: Check out plugin server
              uses: actions/checkout@v2
              with:
                  path: 'plugin-server'

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.8

            - name: Set up Node 14
              uses: actions/setup-node@v2
              with:
                  node-version: 14

            - uses: actions/cache@v2
              with:
                  path: ${{ env.pythonLocation }}
                  key: ${{ env.pythonLocation }}-${{ hashFiles('posthog/requirements.txt') }}

            - name: Install requirements.txt dependencies with pip
              run: |
                  pip install --upgrade pip
                  pip install --upgrade --upgrade-strategy eager -r posthog/requirements.txt

            - name: Set up databases
              env:
                  SECRET_KEY: 'abcdef' # unsafe - for testing only
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/posthog'
                  TEST: 'true'
              run: python posthog/manage.py setup_test_environment

            - name: Install package.json dependencies with Yarn
              run: cd plugin-server && yarn

            - name: Run benchmarks
              env:
                  # Below DB name has `test_` prepended, as that's how Django (ran above) creates the test DB
                  DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/test_posthog'
                  REDIS_URL: 'redis://localhost'
              run: cd plugin-server && yarn benchmark
