name: Containerization

on:
    push:
        branches:
            - master
            - main

jobs:
    build-push:
        name: Build and push container image
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout master
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Login to Public ECR
              uses: docker/login-action@v1
              with:
                  registry: public.ecr.aws
                  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              env:
                  AWS_REGION: us-east-1

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      posthog/plugin-server:latest
                      ghcr.io/posthog/plugin-server:latest
                      public.ecr.aws/p1o5l3m0/posthog-plugin-server:latest
