name: Containerization

on:
    push:
        branches:
            - master
            - main

jobs:
    build-push:
        name: Build and push container image
        runs-on: ubuntu-20.04
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Get package version
              id: version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  PACKAGE_VERSION_TAG="v$PACKAGE_VERSION"
                  if git rev-parse "$PACKAGE_VERSION_TAG"; then
                    IS_NEW_VERSION=false
                  else
                    IS_NEW_VERSION=true
                  fi
                  echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
                  echo "PACKAGE_VERSION_TAG=$PACKAGE_VERSION_TAG" >> $GITHUB_ENV
                  echo "IS_NEW_VERSION=$IS_NEW_VERSION" >> $GITHUB_ENV
                  echo "::set-output name=IS_NEW_VERSION::$IS_NEW_VERSION"

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Log in to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.CR_PAT }}

            - name: Log in to Public ECR
              uses: docker/login-action@v1
              with:
                  registry: public.ecr.aws
                  username: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              env:
                  AWS_REGION: us-east-1

            - name: Build and push latest
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      posthog/plugin-server:latest
                      ghcr.io/posthog/plugin-server:latest
                      public.ecr.aws/p1o5l3m0/posthog-plugin-server:latest

            - name: Build and push new version
              if: steps.version.outputs.IS_NEW_VERSION == 'true'
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: |
                      posthog/plugin-server:${{ steps.version.outputs.PACKAGE_VERSION}}
                      ghcr.io/posthog/plugin-server:${{ steps.version.outputs.PACKAGE_VERSION}}
                      public.ecr.aws/p1o5l3m0/posthog-plugin-server:${{ steps.version.outputs.PACKAGE_VERSION}}
